
name: "well-wisher-1.0"
description: "Greets people"
author: "Aman-zishan"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "bell"
  color: "red"
